name: Deploy to test environment
on: [push, workflow_dispatch]
jobs:
  test-deploy:
    runs-on: Linux
    if: github.ref == 'refs/heads/test'
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: docker compose down
      - run: docker compose up --build -d
      - run: echo "This job's status is ${{ job.status }}."
